Repository readmeio/standards, pull requests merged in 2022-04, with the labels that each got.

#357 fix: dep issues with the root package.json that's breaking eslint
  package-lock.json
  package.json
Labels: bug

#358 chore(deps): bumping out of date deps
  package-lock.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/stylelint-config/package-lock.json
Labels: dependencies

#361 fix(eslint-config): fix false-positive error with TS enums
  packages/eslint-config/typescript.js
Labels: enhancement

#363 feat: supporting node 17
  .github/workflows/ci.yml
  package.json
  packages/eslint-config/package.json
Labels: enhancement
