Repository readmeio/standards, pull requests merged in 2023-08, with the labels that each got.

#719 refactor: consolidate prettier config, load it in spectral
  packages/eslint-config/.prettierrc
  packages/eslint-config/index.js
  packages/eslint-config/prettier.config.js
  packages/spectral-config/package.json
Labels: refactor

#718 feat(spectral): migrate to ESM
  .github/dependabot.yml
  package-lock.json
  packages/spectral-config/.eslintrc
  packages/spectral-config/package.json
  packages/spectral-config/src/functions/alex.js
  packages/spectral-config/src/functions/index.js
  packages/spectral-config/src/functions/sentencePunctuation.js
  packages/spectral-config/src/index.js
  packages/spectral-config/src/rules/alex-component-description.js
  packages/spectral-config/src/rules/alex-component-summary.js
  packages/spectral-config/src/rules/alex-operation-description.js
  packages/spectral-config/src/rules/alex-operation-summary.js
  packages/spectral-config/src/rules/alex-parameter.js
  packages/spectral-config/src/rules/alex-response.js
  packages/spectral-config/src/rules/description-sentence-punctuation.js
  packages/spectral-config/src/rules/index.js
  packages/spectral-config/test/alex-component-description.test.js
  packages/spectral-config/test/alex-component-summary.test.js
  packages/spectral-config/test/alex-operation-description.test.js
  packages/spectral-config/test/alex-operation-summary.test.js
  packages/spectral-config/test/alex-parameter.test.js
  packages/spectral-config/test/alex-response.test.js
  packages/spectral-config/test/description-sentence-punctuation.test.js
Labels: enhancement

#722 fix: more prettier cleanup
  .github/dependabot.yml
  .prettierignore
  packages/eslint-config/prettier.js
  packages/spectral-config/README.md
  packages/stylelint-config/README.md
  packages/stylelint-config/package.json
Labels: bug

#723 feat(eslint): restructuring + vitest support + docs and mocha deprecation
  package-lock.json
  packages/eslint-config/README.md
  packages/eslint-config/docs.js
  packages/eslint-config/package.json
  packages/eslint-config/react.js
  packages/eslint-config/testing.js
  packages/eslint-config/testing/common.config.js
  packages/eslint-config/testing/jest-dom.js
  packages/eslint-config/testing/jest.js
  packages/eslint-config/testing/react.js
  packages/eslint-config/testing/vitest.js
  packages/eslint-config/typescript.js
  packages/spectral-config/package.json
  packages/spectral-config/test/.eslintrc
  packages/spectral-config/test/alex-component-description.test.js
  packages/spectral-config/test/alex-component-summary.test.js
  packages/spectral-config/test/alex-operation-description.test.js
  packages/spectral-config/test/alex-operation-summary.test.js
  packages/spectral-config/test/alex-parameter.test.js
  packages/spectral-config/test/alex-response.test.js
  packages/spectral-config/test/description-sentence-punctuation.test.js
  packages/stylelint-config/.eslintrc.cjs
  packages/stylelint-config/__tests__/__snapshots__/index.test.js.snap
  packages/stylelint-config/__tests__/index.test.js
  packages/stylelint-config/package.json
Labels: enhancement, refactor

#724 fix(spectral-config): partially revert ESM
  packages/spectral-config/.eslintrc
  packages/spectral-config/package.json
  packages/spectral-config/src/functions/alex.js
  packages/spectral-config/src/functions/index.js
  packages/spectral-config/src/functions/sentencePunctuation.js
  packages/spectral-config/src/index.js
  packages/spectral-config/src/rules/alex-component-description.js
  packages/spectral-config/src/rules/alex-component-summary.js
  packages/spectral-config/src/rules/alex-operation-description.js
  packages/spectral-config/src/rules/alex-operation-summary.js
  packages/spectral-config/src/rules/alex-parameter.js
  packages/spectral-config/src/rules/alex-response.js
  packages/spectral-config/src/rules/description-sentence-punctuation.js
  packages/spectral-config/src/rules/index.js
  packages/spectral-config/test/alex-component-description.test.js
  packages/spectral-config/test/alex-component-summary.test.js
  packages/spectral-config/test/alex-operation-description.test.js
  packages/spectral-config/test/alex-operation-summary.test.js
  packages/spectral-config/test/alex-parameter.test.js
  packages/spectral-config/test/alex-response.test.js
  packages/spectral-config/test/description-sentence-punctuation.test.js
Labels: bug

#725 chore(spectral): point `alex` import to `index.js`
  packages/spectral-config/package.json
  packages/spectral-config/src/functions/alex.js
Labels: enhancement, refactor
