Repository readmeio/standards, pull requests merged in 2023-09, with the labels that each got.

#744 revert: get spectral working again
  .github/dependabot.yml
  package-lock.json
  packages/spectral-config/package.json
  packages/spectral-config/src/functions/alex.js
Labels: bug

#748 revert: ESM again
  package-lock.json
  packages/spectral-config/.eslintignore
  packages/spectral-config/.eslintrc
  packages/spectral-config/.gitignore
  packages/spectral-config/.prettierignore
  packages/spectral-config/package.json
  packages/spectral-config/src/functions/alex.js
  packages/spectral-config/src/functions/index.js
  packages/spectral-config/src/functions/sentencePunctuation.js
  packages/spectral-config/src/index.js
  packages/spectral-config/src/rules/alex-component-description.js
  packages/spectral-config/src/rules/alex-component-summary.js
  packages/spectral-config/src/rules/alex-operation-description.js
  packages/spectral-config/src/rules/alex-operation-summary.js
  packages/spectral-config/src/rules/alex-parameter.js
  packages/spectral-config/src/rules/alex-response.js
  packages/spectral-config/src/rules/description-sentence-punctuation.js
  packages/spectral-config/src/rules/index.js
  packages/spectral-config/test/alex-component-description.test.js
  packages/spectral-config/test/alex-component-summary.test.js
  packages/spectral-config/test/alex-operation-description.test.js
  packages/spectral-config/test/alex-operation-summary.test.js
  packages/spectral-config/test/alex-parameter.test.js
  packages/spectral-config/test/alex-response.test.js
  packages/spectral-config/test/description-sentence-punctuation.test.js
  packages/spectral-config/tsup.config.js
Labels: bug

#749 revert(again so sorry): ESM take 3
  package-lock.json
  packages/spectral-config/.eslintignore
  packages/spectral-config/.eslintrc
  packages/spectral-config/.gitignore
  packages/spectral-config/.prettierignore
  packages/spectral-config/package.json
  packages/spectral-config/src/functions/alex.js
  packages/spectral-config/src/functions/index.js
  packages/spectral-config/src/functions/sentencePunctuation.js
  packages/spectral-config/src/index.js
  packages/spectral-config/src/rules/alex-component-description.js
  packages/spectral-config/src/rules/alex-component-summary.js
  packages/spectral-config/src/rules/alex-operation-description.js
  packages/spectral-config/src/rules/alex-operation-summary.js
  packages/spectral-config/src/rules/alex-parameter.js
  packages/spectral-config/src/rules/alex-response.js
  packages/spectral-config/src/rules/description-sentence-punctuation.js
  packages/spectral-config/src/rules/index.js
  packages/spectral-config/test/alex-component-description.test.js
  packages/spectral-config/test/alex-component-summary.test.js
  packages/spectral-config/test/alex-operation-description.test.js
  packages/spectral-config/test/alex-operation-summary.test.js
  packages/spectral-config/test/alex-parameter.test.js
  packages/spectral-config/test/alex-response.test.js
  packages/spectral-config/test/description-sentence-punctuation.test.js
  packages/spectral-config/tsup.config.js
Labels: bug

#750 ci: run prettier on everything
  package.json
  packages/eslint-config/README.md
Labels: enhancement

#751 feat: creation of a new `esm` config for esm codebases
  package-lock.json
  packages/eslint-config/README.md
  packages/eslint-config/esm.js
  packages/eslint-config/package.json
Labels: enhancement

#752 fix(eslint/esm): enable `import/no-commonjs`
  packages/eslint-config/esm.js
Labels: enhancement

#753 ci(eslint-config): add lightweight type-checking
  .prettierignore
  package-lock.json
  package.json
  packages/eslint-config/esm.js
  packages/eslint-config/index.js
  packages/eslint-config/package.json
  packages/eslint-config/prettier.config.js
  packages/eslint-config/react.js
  packages/eslint-config/testing/common.config.js
  packages/eslint-config/testing/jest-dom.js
  packages/eslint-config/testing/jest.js
  packages/eslint-config/testing/react.js
  packages/eslint-config/testing/vitest.js
  packages/eslint-config/tsconfig.json
  packages/eslint-config/typescript.js
Labels: enhancement, refactor
